language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator
xcode_project: ikaten.xcodeproj
xcode_scheme: ikatenTests
notifications:
  email: false
  slack:
    secure: gSvmzrY565uztJehh12WIneeJutHxV/pTTwZRSFC1GPOquFuwLpfoglVNnbHdpCzOkKGm585j16FpDL+VH+UwZ3xjdvj+aydmAkShY+ER1cY+hsSG86/S4QPlIhFVTs95LrwrZfDU3IP8FHMoF+AzxCQsJeQ+rdEUJsq0X6H4OIxA1UlGUuRGf6w5rRJ+hwRXw/VlBXhMkiZ/U6P5m/OeYvgsiOdEogpcGEq6Cs8UfY9Fw7TJkBKD05OB935rzddb31r1QlxjU+or9MN1J6r95jQph+A6SmUb7EL8BYDsEw+2Wkq0syVRFvg6Af4wBg0Tq3RNjELc1tBPkV5hDsOwvwM0XfcZA8M/LJQ3SIek+G7HJ3dR5V+pG3jsWGCdw1T+tuuHxSWgnxYX2Lj7oWaPkmeY6UmsgWCUrrkyTWmWn+CMYIcypaEh6mB1KAGlFnxSiWYODsQj+5G0rhS1Q2T0IKHTvKjZ1UuruVuMAeilNNDrutofNEmUWnYAn3ADk68yabQBkqepQyYO1RpqjtBBzuo4fccYYmEg0H6AEXJdGZ6YNjtDWeJ6y6s/LbGgVx5mRp4yeIaXq3tZmbXInKgT+yZPnN0QDbC6UCQponMY+9V7ZcfP/1FoS4RjdD59ZxrB0JrlqxbH2wMCJgtIYREn/9xM1YWDdr23PBUti1j3gk=
